name: 'finsight'
version: '1.0.0'
config-version: 2

profile: 'finsight'

model-paths:  ["models"]
seed-paths:   ["seeds"]
test-paths:   ["tests"]
analysis-paths: ["analyses"]
macro-paths:  ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  finsight:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table

seeds:
  finsight:
    +schema: gold
